-- ============================================================
-- Reconstructed DDL for schema 'ubec_ui'
-- Source: ubec_ui_schema_documentation_20251231_143725.md (structure only)
--
-- Target database: ubec_protocol  (same DB as ubec_main; ubec_ui is a schema,
--   NOT a separate database — the interface's ui_db_connection.py sets
--   search_path across ubec_main, phenomenal, ubec_ui, public.)
--
-- Version: 1.0.0  (2026-07-02)
-- 15 tables, 8 foreign-key relationships. No enums/arrays (plain integer,
--   varchar, jsonb, inet, uuid, timestamptz). Tables ordered so FK parents
--   precede children. Idempotent: CREATE SCHEMA/TABLE IF NOT EXISTS, and FK
--   constraints added via guarded DO blocks so re-applying is safe.
--
-- License (code): GNU AGPL v3.0
-- This project uses the services of Claude and Anthropic PBC to inform our
-- decisions and recommendations. This project was made possible with the
-- assistance of Claude and Anthropic PBC.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE SCHEMA IF NOT EXISTS "ubec_ui";
SET search_path TO "ubec_ui", public;

-- ------------------------------------------------------------
-- Parent tables (no outgoing FKs to other ubec_ui tables)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "ubec_ui"."users" (
    "id"                     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "uuid"                   uuid NOT NULL DEFAULT uuid_generate_v4(),
    "email"                  varchar(255) NOT NULL,
    "password_hash"          varchar(255),
    "full_name"              varchar(255),
    "display_name"           varchar(100),
    "phone"                  varchar(50),
    "location"               varchar(255),
    "role"                   varchar(50) DEFAULT 'applicant',
    "is_active"              boolean DEFAULT true,
    "is_verified"            boolean DEFAULT false,
    "stellar_address"        varchar(56),
    "last_login_at"          timestamptz,
    "created_at"             timestamptz DEFAULT CURRENT_TIMESTAMP,
    "updated_at"             timestamptz DEFAULT CURRENT_TIMESTAMP,
    "failed_login_attempts"  integer DEFAULT 0,
    "is_locked"              boolean DEFAULT false,
    "locked_until"           timestamptz,
    "password_changed_at"    timestamptz,
    "is_admin"               boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."permissions" (
    "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"         varchar(100) NOT NULL,
    "display_name" varchar(255) NOT NULL,
    "description"  text,
    "category"     varchar(50) NOT NULL DEFAULT 'general',
    "is_system"    boolean DEFAULT false,
    "created_at"   timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."applications" (
    "id"                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "application_type"      varchar(50) NOT NULL,
    "status"                varchar(50) NOT NULL DEFAULT 'pending',
    "reference_number"      varchar(50) NOT NULL,
    "submitted_at"          timestamptz DEFAULT CURRENT_TIMESTAMP,
    "reviewed_at"           timestamptz,
    "decided_at"            timestamptz,
    "contact_name"          varchar(255) NOT NULL,
    "contact_email"         varchar(255) NOT NULL,
    "contact_phone"         varchar(50),
    "location"              varchar(255) NOT NULL,
    "organization_name"     varchar(255),
    "organization_type"     varchar(100),
    "application_data"      jsonb NOT NULL,
    "requested_amount"      integer NOT NULL,
    "approved_amount"       integer,
    "reviewer_notes"        text,
    "reviewed_by"           varchar(255),
    "decision_notes"        text,
    "decided_by"            varchar(255),
    "applicant_references"  jsonb,
    "agreed_terms"          boolean NOT NULL DEFAULT false,
    "agreed_values"         boolean NOT NULL DEFAULT false,
    "confirmation_sent"     boolean DEFAULT false,
    "confirmation_sent_at"  timestamptz,
    "created_at"            timestamptz DEFAULT CURRENT_TIMESTAMP,
    "updated_at"            timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."announcements" (
    "id"                 integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title"              varchar(255) NOT NULL,
    "content"            text NOT NULL,
    "announcement_type"  varchar(50) DEFAULT 'info',
    "is_active"          boolean DEFAULT true,
    "display_from"       timestamptz DEFAULT CURRENT_TIMESTAMP,
    "display_until"      timestamptz,
    "created_by"         varchar(255),
    "created_at"         timestamptz DEFAULT CURRENT_TIMESTAMP,
    "updated_at"         timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."contact_messages" (
    "id"            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"          varchar(255) NOT NULL,
    "email"         varchar(255) NOT NULL,
    "subject"       varchar(255),
    "message"       text NOT NULL,
    "message_type"  varchar(50) DEFAULT 'general',
    "status"        varchar(50) DEFAULT 'new',
    "replied_at"    timestamptz,
    "replied_by"    varchar(255),
    "ip_address"    inet,
    "created_at"    timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."email_log" (
    "id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recipient_email"  varchar(255) NOT NULL,
    "email_type"       varchar(100) NOT NULL,
    "subject"          varchar(255),
    "reference_type"   varchar(50),
    "reference_id"     integer,
    "status"           varchar(50) DEFAULT 'sent',
    "error_message"    text,
    "sent_at"          timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."newsletter_subscribers" (
    "id"                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email"                varchar(255) NOT NULL,
    "name"                 varchar(255),
    "is_active"            boolean DEFAULT true,
    "subscription_source"  varchar(100),
    "confirmed_at"         timestamptz,
    "unsubscribed_at"      timestamptz,
    "created_at"           timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Child tables (FK into users / permissions / applications)
-- ------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "ubec_ui"."activity_log" (
    "id"           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"      integer,
    "action"       varchar(100) NOT NULL,
    "entity_type"  varchar(50),
    "entity_id"    integer,
    "details"      jsonb,
    "ip_address"   inet,
    "user_agent"   text,
    "created_at"   timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."admin_audit_log" (
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"        integer,
    "user_email"     varchar(255),
    "action"         varchar(100) NOT NULL,
    "resource_type"  varchar(100),
    "resource_id"    integer,
    "details"        jsonb,
    "ip_address"     inet,
    "user_agent"     text,
    "created_at"     timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."admin_sessions" (
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"        integer NOT NULL,
    "session_token"  varchar(255) NOT NULL,
    "ip_address"     inet,
    "user_agent"     text,
    "expires_at"     timestamptz NOT NULL,
    "created_at"     timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."user_sessions" (
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"        integer NOT NULL,
    "session_token"  varchar(255) NOT NULL,
    "ip_address"     inet,
    "user_agent"     text,
    "expires_at"     timestamptz NOT NULL,
    "created_at"     timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."password_reset_tokens" (
    "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id"     integer NOT NULL,
    "token"       varchar(255) NOT NULL,
    "expires_at"  timestamptz NOT NULL,
    "used_at"     timestamptz,
    "created_at"  timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."role_permissions" (
    "id"             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "role"           varchar(50) NOT NULL,
    "permission_id"  integer NOT NULL,
    "granted_at"     timestamptz DEFAULT CURRENT_TIMESTAMP,
    "granted_by"     varchar(255)
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."application_documents" (
    "id"              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "application_id"  integer NOT NULL,
    "document_type"   varchar(100) NOT NULL,
    "filename"        varchar(255) NOT NULL,
    "file_path"       varchar(500) NOT NULL,
    "file_size"       integer,
    "mime_type"       varchar(100),
    "uploaded_at"     timestamptz DEFAULT CURRENT_TIMESTAMP,
    "uploaded_by"     varchar(255)
);

CREATE TABLE IF NOT EXISTS "ubec_ui"."application_status_history" (
    "id"              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "application_id"  integer NOT NULL,
    "old_status"      varchar(50),
    "new_status"      varchar(50) NOT NULL,
    "changed_by"      varchar(255),
    "change_reason"   text,
    "changed_at"      timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- Foreign keys (added guarded so re-applying the schema is safe)
-- ------------------------------------------------------------
DO $$ BEGIN
    ALTER TABLE "ubec_ui"."user_sessions"
        ADD CONSTRAINT "user_sessions_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "ubec_ui"."users"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."password_reset_tokens"
        ADD CONSTRAINT "password_reset_tokens_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "ubec_ui"."users"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."admin_sessions"
        ADD CONSTRAINT "admin_sessions_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "ubec_ui"."users"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."admin_audit_log"
        ADD CONSTRAINT "admin_audit_log_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "ubec_ui"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."activity_log"
        ADD CONSTRAINT "activity_log_user_id_fkey"
        FOREIGN KEY ("user_id") REFERENCES "ubec_ui"."users"("id") ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."role_permissions"
        ADD CONSTRAINT "role_permissions_permission_id_fkey"
        FOREIGN KEY ("permission_id") REFERENCES "ubec_ui"."permissions"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."application_status_history"
        ADD CONSTRAINT "application_status_history_application_id_fkey"
        FOREIGN KEY ("application_id") REFERENCES "ubec_ui"."applications"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE "ubec_ui"."application_documents"
        ADD CONSTRAINT "application_documents_application_id_fkey"
        FOREIGN KEY ("application_id") REFERENCES "ubec_ui"."applications"("id") ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
